/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package safariami.manager.prismtoken1;


@jakarta.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2021-02-03")
public enum TokenIssueFlags implements org.apache.thrift.TEnum {
  EXTERNAL_CLOCK(1),
  TID_ADJUST_BDT(2),
  SPECIAL_RESERVED(4);

  private final int value;

  private TokenIssueFlags(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static TokenIssueFlags findByValue(int value) { 
    switch (value) {
      case 1:
        return EXTERNAL_CLOCK;
      case 2:
        return TID_ADJUST_BDT;
      case 4:
        return SPECIAL_RESERVED;
      default:
        return null;
    }
  }
}
